kind = "web"
previewPath = "/"
title = "AR IPTV"
version = "1.0.0"
id = "artifacts/ar-iptv"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 22693

[services.development]
run = "pnpm --filter @workspace/ar-iptv run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/ar-iptv", "run", "build" ]
publicDir = "artifacts/ar-iptv/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "22693"
BASE_PATH = "/"
