export interface Channel {
  id: number;
  name: string;
  url: string;
  country: string;
  countrySlug: string;
  countryFlag: string;
  group: string;
}

const COUNTRY_CODES: Record<string, string> = {
  argentina: "ar",
  colombia: "co",
  russia: "ru",
  usa: "us",
  brazil: "br",
  france: "fr",
  turkey: "tr",
  chile: "cl",
  portugal: "pt",
  spain: "es",
  uk: "gb",
  italy: "it",
  mexico: "mx",
  international: "un",
  ukraine: "ua",
  albania: "al",
  "czech-republic": "cz",
  bulgaria: "bg",
  hungary: "hu",
  germany: "de",
  netherlands: "nl",
  norway: "no",
  israel: "il",
  macau: "mo",
  "hong-kong": "hk",
  india: "in",
  "saudi-arabia": "sa",
  qatar: "qa",
  turkmenistan: "tm",
  romania: "ro",
};

export function getCountryFlagUrl(slug: string): string {
  const code = COUNTRY_CODES[slug.toLowerCase()];
  if (!code) return `https://flagcdn.com/w80/un.png`;
  return `https://flagcdn.com/w80/${code}.png`;
}

export const channels: Channel[] = [
  { id: 1, name: "TNT Sports ARG", url: "https://1nyaler.streamhostingcdn.top/stream/30/index.m3u8", country: "Argentina", countrySlug: "argentina", countryFlag: "🇦🇷", group: "Sport" },
  { id: 2, name: "TyC Sports ARG", url: "https://1nyaler.streamhostingcdn.top/stream/84/index.m3u8", country: "Argentina", countrySlug: "argentina", countryFlag: "🇦🇷", group: "Sport" },
  { id: 3, name: "ESPN LAT", url: "http://181.191.141.7/Live/51334cbb88db0e050c59ef2d28c53491/local-espnlat_720.m3u8", country: "Argentina", countrySlug: "argentina", countryFlag: "🇦🇷", group: "Sport" },
  { id: 4, name: "ESPN ARG", url: "http://181.191.141.7/Live/51334cbb88db0e050c59ef2d28c53491/local-espnar_lng.m3u8", country: "Argentina", countrySlug: "argentina", countryFlag: "🇦🇷", group: "Sport" },
  { id: 5, name: "ESPN 2", url: "http://181.191.141.7/Live/51334cbb88db0e050c59ef2d28c53491/local-espn2ar_lng.m3u8", country: "Argentina", countrySlug: "argentina", countryFlag: "🇦🇷", group: "Sport" },
  { id: 6, name: "ESPN 3", url: "http://181.191.141.7/Live/51334cbb88db0e050c59ef2d28c53491/local-espn3ar_lng.m3u8", country: "Argentina", countrySlug: "argentina", countryFlag: "🇦🇷", group: "Sport" },
  { id: 7, name: "ESPN 3 720p", url: "http://181.191.141.7/Live/51334cbb88db0e050c59ef2d28c53491/local-espn3lat_720.m3u8", country: "Argentina", countrySlug: "argentina", countryFlag: "🇦🇷", group: "Sport" },
  { id: 8, name: "ESPN 4 720p", url: "http://181.191.141.7/Live/51334cbb88db0e050c59ef2d28c53491/local-espn4lat_720.m3u8", country: "Argentina", countrySlug: "argentina", countryFlag: "🇦🇷", group: "Sport" },
  { id: 9, name: "ESPN 4", url: "http://181.191.141.7/Live/51334cbb88db0e050c59ef2d28c53491/local-espn4lat.playlist.m3u8", country: "Argentina", countrySlug: "argentina", countryFlag: "🇦🇷", group: "Sport" },
  { id: 10, name: "ESPN 5 720p", url: "http://181.191.141.7/Live/51334cbb88db0e050c59ef2d28c53491/local-espn5lat_720.m3u8", country: "Argentina", countrySlug: "argentina", countryFlag: "🇦🇷", group: "Sport" },
  { id: 11, name: "ESPN 6", url: "http://181.191.141.7/Live/51334cbb88db0e050c59ef2d28c53491/local-espn6lat_720.m3u8", country: "Argentina", countrySlug: "argentina", countryFlag: "🇦🇷", group: "Sport" },
  { id: 12, name: "ESPN 7", url: "http://181.191.141.7/Live/51334cbb88db0e050c59ef2d28c53491/local-espn7lt_720.m3u8", country: "Argentina", countrySlug: "argentina", countryFlag: "🇦🇷", group: "Sport" },
  { id: 13, name: "ESPN PREMIUM", url: "http://181.191.141.7/Live/51334cbb88db0e050c59ef2d28c53491/local-espnpremar_lng.m3u8", country: "Argentina", countrySlug: "argentina", countryFlag: "🇦🇷", group: "Sport" },
  { id: 14, name: "ESPN PREMIUM 720p", url: "http://181.191.141.7/Live/51334cbb88db0e050c59ef2d28c53491/local-espnpremlat_720.m3u8", country: "Argentina", countrySlug: "argentina", countryFlag: "🇦🇷", group: "Sport" },
  { id: 15, name: "FOX SPORTS", url: "http://181.191.141.7/Live/51334cbb88db0e050c59ef2d28c53491/local-fox1ar_720.m3u8", country: "Argentina", countrySlug: "argentina", countryFlag: "🇦🇷", group: "Sport" },
  { id: 16, name: "FOX SPORT 2", url: "http://181.191.141.7/Live/51334cbb88db0e050c59ef2d28c53491/local-fox2ar.playlist.m3u8", country: "Argentina", countrySlug: "argentina", countryFlag: "🇦🇷", group: "Sport" },
  { id: 17, name: "Win Sports", url: "http://181.78.17.52:8000/play/a0pw/index.m3u8", country: "Colombia", countrySlug: "colombia", countryFlag: "🇨🇴", group: "Sport" },
  { id: 18, name: "WIN SPORTS", url: "http://181.78.71.71:18000/play/a03p/index.m3u8", country: "Colombia", countrySlug: "colombia", countryFlag: "🇨🇴", group: "Sport" },
  { id: 19, name: "win+", url: "http://190.60.37.154:45000/play/a00q/index.m3u8", country: "Colombia", countrySlug: "colombia", countryFlag: "🇨🇴", group: "Sport" },
  { id: 20, name: "TYC", url: "http://190.60.37.154:45000/play/a05a/index.m3u8", country: "Argentina", countrySlug: "argentina", countryFlag: "🇦🇷", group: "Sport" },
  { id: 21, name: "DSPORTS 1", url: "http://190.117.20.37:8000/play/a08d/index.m3u8", country: "Argentina", countrySlug: "argentina", countryFlag: "🇦🇷", group: "Sport" },
  { id: 22, name: "DSports", url: "http://205.235.6.29:8000/play/a0nq/index.m3u8", country: "Argentina", countrySlug: "argentina", countryFlag: "🇦🇷", group: "Sport" },
  { id: 23, name: "espn premium", url: "http://205.235.6.29:8000/play/a0pz/index.m3u8", country: "Argentina", countrySlug: "argentina", countryFlag: "🇦🇷", group: "Sport" },
  { id: 24, name: "tnt sport", url: "http://205.235.6.29:8000/play/a0xa/index.m3u8", country: "Argentina", countrySlug: "argentina", countryFlag: "🇦🇷", group: "Sport" },
  { id: 25, name: "tnt sport premium", url: "http://205.235.6.29:8000/play/a104/index.m3u8", country: "Argentina", countrySlug: "argentina", countryFlag: "🇦🇷", group: "Sport" },
  { id: 26, name: "espn", url: "http://205.235.6.29:8000/play/a0zf/index.m3u8", country: "Argentina", countrySlug: "argentina", countryFlag: "🇦🇷", group: "Sport" },
  { id: 27, name: "espn 7", url: "http://205.235.6.29:8000/play/a0zv/index.m3u8", country: "Argentina", countrySlug: "argentina", countryFlag: "🇦🇷", group: "Sport" },
  { id: 28, name: "WIN", url: "http://217.26.190.76:8888/play/a06a/index.m3u8", country: "Colombia", countrySlug: "colombia", countryFlag: "🇨🇴", group: "Sport" },
  { id: 29, name: "DSPORTS +", url: "http://217.26.190.76:8888/play/a0jb/index.m3u8", country: "Argentina", countrySlug: "argentina", countryFlag: "🇦🇷", group: "Sport" },
  { id: 30, name: "DIRECTV SPORTS", url: "http://217.26.190.76:8888/play/a0co/index.m3u8", country: "Argentina", countrySlug: "argentina", countryFlag: "🇦🇷", group: "Sport" },
  { id: 31, name: "DSports", url: "http://38.226.210.46:8000/play/A008/index.m3u8", country: "Argentina", countrySlug: "argentina", countryFlag: "🇦🇷", group: "Sport" },
  { id: 32, name: "dsport", url: "http://jumangis.cloud:2082/JairoVargas/5T5wLJjTbu/117708", country: "Argentina", countrySlug: "argentina", countryFlag: "🇦🇷", group: "Sport" },
  { id: 33, name: "TUDN USA", url: "http://m3u.tvcluboficial.com/m/m/957.m3u8", country: "USA", countrySlug: "usa", countryFlag: "🇺🇸", group: "Sport" },
  { id: 34, name: "win sport", url: "http://m3u.tvcluboficial.com/m/m/1039.m3u8", country: "Colombia", countrySlug: "colombia", countryFlag: "🇨🇴", group: "Sport" },
  { id: 35, name: "win sports+", url: "http://m3u.tvcluboficial.com/m/m/1042.m3u8", country: "Colombia", countrySlug: "colombia", countryFlag: "🇨🇴", group: "Sport" },
  { id: 36, name: "ADRENALINA SPORTS", url: "https://tv.topmediatv.net:25463/live/TopMediaWeb/bOteTR8ED1/98.m3u8", country: "International", countrySlug: "international", countryFlag: "🌍", group: "Sport" },
  { id: 37, name: "CLARO SPORTS", url: "https://tv.topmediatv.net:25463/live/TopMediaWeb/bOteTR8ED1/103.m3u8", country: "Colombia", countrySlug: "colombia", countryFlag: "🇨🇴", group: "Sport" },
  { id: 38, name: "TNT SPORTS CHILE", url: "https://tv.topmediatv.net:25463/live/TopMediaWeb/bOteTR8ED1/462.m3u8", country: "Chile", countrySlug: "chile", countryFlag: "🇨🇱", group: "Sport" },
  { id: 39, name: "EUROSPORT 1", url: "https://tv.topmediatv.net:25463/live/TopMediaWeb/bOteTR8ED1/618.m3u8", country: "International", countrySlug: "international", countryFlag: "🌍", group: "Sport" },
  { id: 40, name: "EUROSPORT 2", url: "https://tv.topmediatv.net:25463/live/TopMediaWeb/bOteTR8ED1/619.m3u8", country: "International", countrySlug: "international", countryFlag: "🌍", group: "Sport" },
  { id: 41, name: "BEIN SPORTS Ñ", url: "https://amg01334-beinsportsllc-beinxtraesp-localnow-aekzc.amagi.tv/playlist.m3u8", country: "International", countrySlug: "international", countryFlag: "🌍", group: "Sport" },
  { id: 42, name: "DAZN F1", url: "https://tv.topmediatv.net:25463/live/TopMediaWeb/bOteTR8ED1/374.m3u8", country: "International", countrySlug: "international", countryFlag: "🌍", group: "Sport" },
  { id: 43, name: "TUDN 1", url: "https://tv.topmediatv.net:25463/live/TopMediaWeb/bOteTR8ED1/128.m3u8", country: "USA", countrySlug: "usa", countryFlag: "🇺🇸", group: "Sport" },
  { id: 44, name: "ESPN DEPORTES", url: "https://tv.topmediatv.net:25463/live/TopMediaWeb/bOteTR8ED1/112.m3u8", country: "USA", countrySlug: "usa", countryFlag: "🇺🇸", group: "Sport" },
  { id: 45, name: "WIN SPORTS PLUS", url: "https://tv.topmediatv.net:25463/live/TopMediaWeb/bOteTR8ED1/126.m3u8", country: "Colombia", countrySlug: "colombia", countryFlag: "🇨🇴", group: "Sport" },
  { id: 46, name: "TUDN 2", url: "https://tv.topmediatv.net:25463/live/TopMediaWeb/bOteTR8ED1/791.m3u8", country: "USA", countrySlug: "usa", countryFlag: "🇺🇸", group: "Sport" },
  { id: 47, name: "ESPN PREMIUM CHI", url: "http://186.33.40.97:8789/play/22", country: "Chile", countrySlug: "chile", countryFlag: "🇨🇱", group: "Sport" },
  { id: 48, name: "ETC TV", url: "https://tv.topmediatv.net:25463/live/TopMediaWeb/bOteTR8ED1/578.m3u8", country: "Chile", countrySlug: "chile", countryFlag: "🇨🇱", group: "Entertainment" },
  { id: 49, name: "ESPN", url: "https://tv.topmediatv.net:25463/live/TopMediaWeb/bOteTR8ED1/107.m3u8", country: "International", countrySlug: "international", countryFlag: "🌍", group: "Sport" },
  { id: 50, name: "ESPN CO", url: "https://tv.topmediatv.net:25463/live/TopMediaWeb/bOteTR8ED1/10685.m3u8", country: "Colombia", countrySlug: "colombia", countryFlag: "🇨🇴", group: "Sport" },
  { id: 51, name: "ESPN 2", url: "https://tv.topmediatv.net:25463/live/TopMediaWeb/bOteTR8ED1/108.m3u8", country: "International", countrySlug: "international", countryFlag: "🌍", group: "Sport" },
  { id: 52, name: "ESPN 3", url: "https://tv.topmediatv.net:25463/live/TopMediaWeb/bOteTR8ED1/109.m3u8", country: "International", countrySlug: "international", countryFlag: "🌍", group: "Sport" },
  { id: 53, name: "ESPN 4", url: "https://tv.topmediatv.net:25463/live/TopMediaWeb/bOteTR8ED1/110.m3u8", country: "International", countrySlug: "international", countryFlag: "🌍", group: "Sport" },
  { id: 54, name: "CLARO SPORTS", url: "http://162.19.255.233:8080/play/UNbAl57p9hXZClOu56FCTUSaL5q1VtS-E1wCfb1nvO4/m3u8", country: "Colombia", countrySlug: "colombia", countryFlag: "🇨🇴", group: "Sport" },
  { id: 55, name: "FOX", url: "https://tv.topmediatv.net:25463/live/TopMediaWeb/bOteTR8ED1/459.m3u8", country: "International", countrySlug: "international", countryFlag: "🌍", group: "Sport" },
  { id: 56, name: "FOX 2", url: "https://tv.topmediatv.net:25463/live/TopMediaWeb/bOteTR8ED1/10532.m3u8", country: "International", countrySlug: "international", countryFlag: "🌍", group: "Sport" },
  { id: 57, name: "WIN SPORTS", url: "http://190.60.39.195:8000/play/a0ug/index.m3u8", country: "Colombia", countrySlug: "colombia", countryFlag: "🇨🇴", group: "Sport" },
  { id: 58, name: "ESPN PREMIUN 1", url: "http://190.7.19.197:232/play/a038/index.m3u8", country: "Argentina", countrySlug: "argentina", countryFlag: "🇦🇷", group: "Sport" },
  { id: 59, name: "ESPN 5", url: "http://181.118.158.103:8000/play/a03c/index.m3u8", country: "Argentina", countrySlug: "argentina", countryFlag: "🇦🇷", group: "Sport" },
  { id: 60, name: "ESPN ARG", url: "http://45.170.130.224:8000/play/a04l/index.m3u8", country: "Argentina", countrySlug: "argentina", countryFlag: "🇦🇷", group: "Sport" },
  { id: 61, name: "TYC SPORTS", url: "https://tv.topmediatv.net:25463/live/TopMediaWeb/bOteTR8ED1/8631.m3u8", country: "Argentina", countrySlug: "argentina", countryFlag: "🇦🇷", group: "Sport" },
  { id: 62, name: "TYC SPORTS Internacional", url: "http://190.7.19.197:232/play/a04w/index.m3u8", country: "Argentina", countrySlug: "argentina", countryFlag: "🇦🇷", group: "Sport" },
  { id: 63, name: "DAZN 1", url: "http://znty.dyndns.org:5010/hls/eleven1.m3u8", country: "International", countrySlug: "international", countryFlag: "🌍", group: "Sport" },
  { id: 64, name: "DAZN 2", url: "http://znty.dyndns.org:5010/hls/eleven2.m3u8", country: "International", countrySlug: "international", countryFlag: "🌍", group: "Sport" },
  { id: 65, name: "DAZN 3", url: "http://znty.dyndns.org:5010/hls/eleven3.m3u8", country: "International", countrySlug: "international", countryFlag: "🌍", group: "Sport" },
  { id: 66, name: "DAZN 4", url: "http://znty.dyndns.org:5010/hls/eleven4.m3u8", country: "International", countrySlug: "international", countryFlag: "🌍", group: "Sport" },
  { id: 67, name: "DAZN 5", url: "http://znty.dyndns.org:5010/hls/eleven5.m3u8", country: "International", countrySlug: "international", countryFlag: "🌍", group: "Sport" },
  { id: 68, name: "МАТЧ! ФУТБОЛ 2HD", url: "http://193.25.8.59:8000/fut2", country: "Russia", countrySlug: "russia", countryFlag: "🇷🇺", group: "Sport" },
  { id: 69, name: "SKY SPORT LALIGA", url: "http://179.60.224.196:8000/play/a0i7/index.m3u8", country: "Mexico", countrySlug: "mexico", countryFlag: "🇲🇽", group: "Sport" },
  { id: 70, name: "LIG", url: "http://200.115.120.1:8000/play/ca124/index.m3u8", country: "Spain", countrySlug: "spain", countryFlag: "🇪🇸", group: "Sport" },
  { id: 71, name: "МАТЧ! ФУТБОЛ 2HD", url: "http://cdntv.online/low/9mlxywika2/56.m3u8", country: "Russia", countrySlug: "russia", countryFlag: "🇷🇺", group: "Sport" },
  { id: 72, name: "TDM Desporto", url: "http://cdn6.163189.xyz/163189/amty", country: "Macau", countrySlug: "macau", countryFlag: "🇲🇴", group: "Sport" },
  { id: 73, name: "IDMANTV", url: "https://str2.yodacdn.net/idman_300_to_small/tracks-v1a1/mono.m3u8", country: "Turkey", countrySlug: "turkey", countryFlag: "🇹🇷", group: "Sport" },
  { id: 74, name: "MAX SPORT 4", url: "http://77.46.130.252:99/maxsport4", country: "Bulgaria", countrySlug: "bulgaria", countryFlag: "🇧🇬", group: "Sport" },
  { id: 75, name: "SKY SPORT LALIGA", url: "http://181.78.109.48:9998/play/a06r/index.m3u8", country: "Mexico", countrySlug: "mexico", countryFlag: "🇲🇽", group: "Sport" },
  { id: 76, name: "OTT CLUB", url: "http://czrb8vng.ottclub.xyz/iptv/AHMQNVLWUTM5PW/6554/index.m3u8", country: "Russia", countrySlug: "russia", countryFlag: "🇷🇺", group: "Sport" },
  { id: 77, name: "Digi Sport 2", url: "http://91.201.172.14:35006/", country: "Romania", countrySlug: "romania", countryFlag: "🇷🇴", group: "Sport" },
  { id: 78, name: "Матч!", url: "http://catchup.videoline.ru/match/tracks-v1a1/mono.m3u8", country: "Russia", countrySlug: "russia", countryFlag: "🇷🇺", group: "Sport" },
  { id: 79, name: "Матч! 2", url: "http://cdntv.online/low/9mlxywika2/48.m3u8", country: "Russia", countrySlug: "russia", countryFlag: "🇷🇺", group: "Sport" },
  { id: 80, name: "ESPN 2 ARG", url: "http://181.205.130.194:4000/play/a07i", country: "Argentina", countrySlug: "argentina", countryFlag: "🇦🇷", group: "Sport" },
  { id: 81, name: "ESPN 2 ARG 2", url: "http://191.97.49.82:8001/play/a00m/index.m3u8", country: "Argentina", countrySlug: "argentina", countryFlag: "🇦🇷", group: "Sport" },
  { id: 82, name: "Dazn 1 PT", url: "http://wo0dyefk.dienalt.org/iptv/DV3AC2Q6YSR9XE/2531/index.m3u8", country: "Portugal", countrySlug: "portugal", countryFlag: "🇵🇹", group: "Sport" },
  { id: 83, name: "Dazn 1 PT", url: "http://wo0dyefk.dienalt.org/iptv/DV3AC2Q6YSR9XE/19158/index.m3u8", country: "Portugal", countrySlug: "portugal", countryFlag: "🇵🇹", group: "Sport" },
  { id: 84, name: "Dazn 2 PT", url: "http://wo0dyefk.dienalt.org/iptv/DV3AC2Q6YSR9XE/2532/index.m3u8", country: "Portugal", countrySlug: "portugal", countryFlag: "🇵🇹", group: "Sport" },
  { id: 85, name: "Dazn 3 PT", url: "http://wo0dyefk.dienalt.org/iptv/DV3AC2Q6YSR9XE/7062/index.m3u8", country: "Portugal", countrySlug: "portugal", countryFlag: "🇵🇹", group: "Sport" },
  { id: 86, name: "Dazn 4 PT", url: "http://wo0dyefk.dienalt.org/iptv/DV3AC2Q6YSR9XE/2534/index.m3u8", country: "Portugal", countrySlug: "portugal", countryFlag: "🇵🇹", group: "Sport" },
  { id: 87, name: "Dazn 5 PT", url: "http://wo0dyefk.dienalt.org/iptv/DV3AC2Q6YSR9XE/2535/index.m3u8", country: "Portugal", countrySlug: "portugal", countryFlag: "🇵🇹", group: "Sport" },
  { id: 88, name: "TNT SPORTS PREMIUM", url: "http://200.115.120.1:8000/play/ca040/index.m3u8", country: "UK", countrySlug: "uk", countryFlag: "🇬🇧", group: "Sport" },
  { id: 89, name: "BEIN 3 FR", url: "http://145.239.5.177/559/mpegts", country: "France", countrySlug: "france", countryFlag: "🇫🇷", group: "Sport" },
  { id: 90, name: "Bein Sport 1 FR", url: "http://99.27.51.147:8080/BeinSport/index.m3u8", country: "France", countrySlug: "france", countryFlag: "🇫🇷", group: "Sport" },
  { id: 91, name: "Bein Sport 3 FR", url: "http://99.27.51.147:8080/BeinSport3/index.m3u8", country: "France", countrySlug: "france", countryFlag: "🇫🇷", group: "Sport" },
  { id: 92, name: "CANAL+ Sport FR", url: "http://151.80.18.177:86/Canal+_sport_HD/index.m3u8", country: "France", countrySlug: "france", countryFlag: "🇫🇷", group: "Sport" },
  { id: 93, name: "Setanta Sport 1 RU", url: "http://cdntv.online/low/9mlxywika2/1021.m3u8", country: "Russia", countrySlug: "russia", countryFlag: "🇷🇺", group: "Sport" },
  { id: 94, name: "Setanta Sport 2 RU", url: "http://cdntv.online/low/9mlxywika2/1022.m3u8", country: "Russia", countrySlug: "russia", countryFlag: "🇷🇺", group: "Sport" },
  { id: 95, name: "Матч! 3", url: "http://185.46.48.18:80/match/tracks-v1a1/mono.m3u8", country: "Russia", countrySlug: "russia", countryFlag: "🇷🇺", group: "Sport" },
  { id: 96, name: "МАТЧ! ФУТБОЛ 1HD", url: "http://193.25.8.59:8000/fut", country: "Russia", countrySlug: "russia", countryFlag: "🇷🇺", group: "Sport" },
  { id: 97, name: "МАТЧ! ФУТБОЛ 1HD 2", url: "http://cdntv.online/low/9mlxywika2/55.m3u8", country: "Russia", countrySlug: "russia", countryFlag: "🇷🇺", group: "Sport" },
  { id: 98, name: "МАТЧ! ФУТБОЛ 3HD", url: "http://cdntv.online/low/9mlxywika2/57.m3u8", country: "Russia", countrySlug: "russia", countryFlag: "🇷🇺", group: "Sport" },
  { id: 99, name: "Setanta Sport UA", url: "http://217.174.225.146/hls/ch004_720/index.m3u8", country: "Ukraine", countrySlug: "ukraine", countryFlag: "🇺🇦", group: "Sport" },
  { id: 100, name: "Суспільне Kiev Спорт HD", url: "https://tva.in.ua/live/susp-sport.m3u8", country: "Ukraine", countrySlug: "ukraine", countryFlag: "🇺🇦", group: "Sport" },
  { id: 101, name: "Super Sport 1 AL", url: "http://93.93.113.95:25461/TV-Berati/XtreamCodes/494", country: "Albania", countrySlug: "albania", countryFlag: "🇦🇱", group: "Sport" },
  { id: 102, name: "Super Sport 2 AL", url: "http://93.93.113.95:25461/TV-Berati/XtreamCodes/495", country: "Albania", countrySlug: "albania", countryFlag: "🇦🇱", group: "Sport" },
  { id: 103, name: "RTSH Sport AL", url: "http://217.73.139.200:5443/play/a01d", country: "Albania", countrySlug: "albania", countryFlag: "🇦🇱", group: "Sport" },
  { id: 104, name: "NOVA SPORT 1 HD CZ", url: "http://wo0dyefk.dienalt.org/iptv/DV3AC2Q6YSR9XE/2555/index.m3u8", country: "Czech Republic", countrySlug: "czech-republic", countryFlag: "🇨🇿", group: "Sport" },
  { id: 105, name: "CT SPORT HD CZ", url: "http://88.212.15.19/live/test_ctsport_25p/playlist.m3u8", country: "Czech Republic", countrySlug: "czech-republic", countryFlag: "🇨🇿", group: "Sport" },
  { id: 106, name: "SPORT 1 HD CZ", url: "http://88.212.15.19/live/test_sport1_25p/playlist.m3u8", country: "Czech Republic", countrySlug: "czech-republic", countryFlag: "🇨🇿", group: "Sport" },
  { id: 107, name: "SPORT 2 HD CZ", url: "http://88.212.15.19/live/test_sport_2/playlist.m3u8", country: "Czech Republic", countrySlug: "czech-republic", countryFlag: "🇨🇿", group: "Sport" },
  { id: 108, name: "ARENA SPORT 1 CZ", url: "http://88.212.15.19/live/test_arenasport/playlist.m3u8", country: "Czech Republic", countrySlug: "czech-republic", countryFlag: "🇨🇿", group: "Sport" },
  { id: 109, name: "ARENA SPORT 2 CZ", url: "http://88.212.15.19/live/test_arenasport_dva/playlist.m3u8", country: "Czech Republic", countrySlug: "czech-republic", countryFlag: "🇨🇿", group: "Sport" },
  { id: 110, name: "MAX SPORT 1 BG", url: "http://77.46.130.252:99/maxsport1", country: "Bulgaria", countrySlug: "bulgaria", countryFlag: "🇧🇬", group: "Sport" },
  { id: 111, name: "MAX SPORT 2 BG", url: "http://77.46.130.252:99/maxsport2", country: "Bulgaria", countrySlug: "bulgaria", countryFlag: "🇧🇬", group: "Sport" },
  { id: 112, name: "MAX SPORT 3 BG", url: "http://77.46.130.252:99/maxsport3", country: "Bulgaria", countrySlug: "bulgaria", countryFlag: "🇧🇬", group: "Sport" },
  { id: 113, name: "M4 Sport HU", url: "http://46.149.191.217:9010/play/a017", country: "Hungary", countrySlug: "hungary", countryFlag: "🇭🇺", group: "Sport" },
  { id: 114, name: "Sportdigital DE", url: "https://jmp2.uk/stvp-ATAJ0500433A", country: "Germany", countrySlug: "germany", countryFlag: "🇩🇪", group: "Sport" },
  { id: 115, name: "ZIGGO SPORT 2 HD NL", url: "http://wo0dyefk.dienalt.org/iptv/DV3AC2Q6YSR9XE/2561/index.m3u8", country: "Netherlands", countrySlug: "netherlands", countryFlag: "🇳🇱", group: "Sport" },
  { id: 116, name: "ZIGGO SPORT 3 HD NL", url: "http://wo0dyefk.dienalt.org/iptv/DV3AC2Q6YSR9XE/2559/index.m3u8", country: "Netherlands", countrySlug: "netherlands", countryFlag: "🇳🇱", group: "Sport" },
  { id: 117, name: "ZIGGO SPORT LIVE NL", url: "http://wo0dyefk.dienalt.org/iptv/DV3AC2Q6YSR9XE/2560/index.m3u8", country: "Netherlands", countrySlug: "netherlands", countryFlag: "🇳🇱", group: "Sport" },
  { id: 118, name: "2TV Sport NO", url: "https://tv.cdn.xsg.ge/gpb-2tv/index.m3u8", country: "Norway", countrySlug: "norway", countryFlag: "🇳🇴", group: "Sport" },
  { id: 119, name: "5 SPORT IL", url: "http://wo0dyefk.dienalt.org/iptv/DV3AC2Q6YSR9XE/2558/index.m3u8", country: "Israel", countrySlug: "israel", countryFlag: "🇮🇱", group: "Sport" },
  { id: 120, name: "TELEFE", url: "http://200.115.120.1:8000/play/ca016/index.m3u8", country: "Argentina", countrySlug: "argentina", countryFlag: "🇦🇷", group: "Entertainment" },
  { id: 121, name: "CAZE TV 1", url: "https://dfr80qz435crc.cloudfront.net/MNOP/Amagi/Caze/Caze_TV_BR/Caze_TV.m3u8", country: "Brazil", countrySlug: "brazil", countryFlag: "🇧🇷", group: "Entertainment" },
  { id: 122, name: "REAL MADRID TV", url: "https://rmtv.akamaized.net/hls/live/2043153/rmtv-es-web/bitrate_3.m3u8", country: "Spain", countrySlug: "spain", countryFlag: "🇪🇸", group: "Sport" },
  { id: 123, name: "BEIN SPORT EXTRA ES", url: "https://bein-esp-xumo.amagi.tv/playlistR1080p.m3u8", country: "Spain", countrySlug: "spain", countryFlag: "🇪🇸", group: "Sport" },
  { id: 124, name: "TELEMUNDO MX", url: "https://nbculocallive.akamaized.net/hls/live/2037499/puertorico/stream1/master.m3u8", country: "Mexico", countrySlug: "mexico", countryFlag: "🇲🇽", group: "Entertainment" },
  { id: 125, name: "MTR Sports-1 UK", url: "https://cdn-uw2-prod.tsv2.amagi.tv/linear/amg02873-kravemedia-mtrspt1-distrotv/playlist.m3u8", country: "UK", countrySlug: "uk", countryFlag: "🇬🇧", group: "Sport" },
  { id: 126, name: "X SPORT RU", url: "http://iptv.prosto.tv:7000/ch109/video.m3u8", country: "Russia", countrySlug: "russia", countryFlag: "🇷🇺", group: "Sport" },
  { id: 127, name: "Turkmenistan Sport", url: "https://alpha.tv.online.tm/legacyhls/ch004_720/index.m3u8", country: "Turkmenistan", countrySlug: "turkmenistan", countryFlag: "🇹🇲", group: "Sport" },
  { id: 128, name: "SPORT ITALIA", url: "https://amg01370-italiansportcom-sportitalia-rakuten-3hmdb.amagi.tv/amRdirect/ads_pod_type=playerpage_midroll&ads_env=prod&ads_ppid=&ads_rtvid=271861&ads_streaming_id=4f185419-74f6-4564-8ea9-4cdc60746e2f&ads_amagi_channel=781&ads_device_type=web&ads_device_model=&ads_device_year=&ads_player_width=&ads_rtv_content_language=ita&ads_market=it&ads_rtv_content_id=3741&ads_device_make=&ads_user_type=visitor&ads_content_classification=6&ads_gdpr_consent=&ads_device_lmt=1&ads_player_height=&uid=1gnmqg5gu-qsvc-bfo-gaq3-3dgjgexshpe/hls/amagi_hls_data_rakutenAA-sportitalia-rakuten/CDN/1920x1080_4540800/chunklist.m3u8", country: "Italy", countrySlug: "italy", countryFlag: "🇮🇹", group: "Sport" },
  { id: 129, name: "TR Sport IT", url: "https://livetr.teleromagna.it/mia/live/playlist.m3u8", country: "Italy", countrySlug: "italy", countryFlag: "🇮🇹", group: "Sport" },
  { id: 130, name: "L'Equipe FR", url: "https://jmp2.uk/stvp-FR200016Y5", country: "France", countrySlug: "france", countryFlag: "🇫🇷", group: "Sport" },
  { id: 131, name: "INFOSPORT FR", url: "http://212.102.60.80/Infosport/index.m3u8", country: "France", countrySlug: "france", countryFlag: "🇫🇷", group: "News" },
  { id: 132, name: "ON Sports+ HK", url: "https://freem3u.xyz/api/live/play.m3u8", country: "Hong Kong", countrySlug: "hong-kong", countryFlag: "🇭🇰", group: "Sport" },
  { id: 133, name: "Fox Sports IN", url: "http://y3fqd48g.megatv.fun/iptv/NRLXRWSBWBPLN4/19146/index.m3u8", country: "India", countrySlug: "india", countryFlag: "🇮🇳", group: "Sport" },
  { id: 134, name: "MMN Sport SA", url: "http://mmn.mypsx.net:1935/live/mmnhdsport/chunklist.m3u8", country: "Saudi Arabia", countrySlug: "saudi-arabia", countryFlag: "🇸🇦", group: "Sport" },
  { id: 135, name: "MASR QA", url: "https://shls-masr-ak.akamaized.net/out/v1/d5036cabf11e45bf9d0db410ca135c18/index.m3u8", country: "Qatar", countrySlug: "qatar", countryFlag: "🇶🇦", group: "Sport" },
  { id: 136, name: "TELETRAK CL", url: "http://unlimited6-cl.dps.live/sportinghd/sportinghd.smil/playlist.m3u8", country: "Chile", countrySlug: "chile", countryFlag: "🇨🇱", group: "Sport" },
  { id: 137, name: "Sport5 IL", url: "https://rgelive.akamaized.net/hls/live/2043151/radiolive/playlist.m3u8", country: "Israel", countrySlug: "israel", countryFlag: "🇮🇱", group: "Sport" },
  { id: 138, name: "Sport5 IL 2", url: "https://rgelive.akamaized.net/hls/live/2043095/live3/playlist.m3u8", country: "Israel", countrySlug: "israel", countryFlag: "🇮🇱", group: "Sport" },
  { id: 139, name: "TUDN MX", url: "http://45.5.119.43:4000/play/a05q/index.m3u8", country: "Mexico", countrySlug: "mexico", countryFlag: "🇲🇽", group: "Sport" },
  { id: 140, name: "ESPN CO 2", url: "http://200.10.30.241:8000/play/a01r/index.m3u8", country: "Colombia", countrySlug: "colombia", countryFlag: "🇨🇴", group: "Sport" },
  { id: 141, name: "Claro Sports 2 CO", url: "http://45.5.118.152:8000/play/a0ah/index.m3u8", country: "Colombia", countrySlug: "colombia", countryFlag: "🇨🇴", group: "Sport" },
  { id: 142, name: "Movistar Deportes", url: "http://38.226.210.46:8000/play/a06d/index.m3u8", country: "Colombia", countrySlug: "colombia", countryFlag: "🇨🇴", group: "Sport" },
  { id: 143, name: "Tigo Sports CO", url: "http://181.78.17.52:8000/play/a0rq/index.m3u8", country: "Colombia", countrySlug: "colombia", countryFlag: "🇨🇴", group: "Sport" },
  { id: 144, name: "Via X Sport CL", url: "http://38.226.49.253:8000/play/a042/index.m3u8", country: "Chile", countrySlug: "chile", countryFlag: "🇨🇱", group: "Sport" },
  { id: 145, name: "BEIN SPORTS 2 Turkey", url: "https://andro.okan11gote12sokan.cfd/checklist/androstreamlivebs2.m3u8", country: "Turkey", countrySlug: "turkey", countryFlag: "🇹🇷", group: "Sport" },
  { id: 146, name: "BEIN SPORTS 3 Turkey", url: "https://andro.okan11gote12sokan.cfd/checklist/androstreamlivebs3.m3u8", country: "Turkey", countrySlug: "turkey", countryFlag: "🇹🇷", group: "Sport" },
  { id: 147, name: "BEIN SPORTS 4 Turkey", url: "https://andro.okan11gote12sokan.cfd/checklist/androstreamlivebs4.m3u8", country: "Turkey", countrySlug: "turkey", countryFlag: "🇹🇷", group: "Sport" },
  { id: 148, name: "BEIN SPORTS 5 Turkey", url: "https://andro.226503.xyz/checklist/androstreamlivebs5.m3u8", country: "Turkey", countrySlug: "turkey", countryFlag: "🇹🇷", group: "Sport" },
  { id: 149, name: "NBC Team USA", url: "https://amg01416-amg01416c4-firetv-us-4522.playouts.now.amagi.tv/playlist.m3u8", country: "USA", countrySlug: "usa", countryFlag: "🇺🇸", group: "Sport" },
  { id: 150, name: "AYM Sports TR", url: "https://aym-as.otteravision.com/aym/as/as.m3u8", country: "Turkey", countrySlug: "turkey", countryFlag: "🇹🇷", group: "Sport" },
  { id: 151, name: "BEK Sports West USA", url: "https://cdn3.wowza.com/5/ZWQ1K2NYTmpFbGsr/BEK-WOWZA-1/smil:BEKPRIMEW.smil/.m3u8", country: "USA", countrySlug: "usa", countryFlag: "🇺🇸", group: "Sport" },
  { id: 152, name: "RS News BR", url: "https://video07.logicahost.com.br/rsnews01/rsnews01/playlist.m3u8", country: "Brazil", countrySlug: "brazil", countryFlag: "🇧🇷", group: "News" },
  { id: 153, name: "RS Sports 1 BR", url: "https://video07.logicahost.com.br/rssports01/rssports01/playlist.m3u8", country: "Brazil", countrySlug: "brazil", countryFlag: "🇧🇷", group: "Sport" },
  { id: 154, name: "RS Sports 2 BR", url: "https://video07.logicahost.com.br/rssports02/rssports02/playlist.m3u8", country: "Brazil", countrySlug: "brazil", countryFlag: "🇧🇷", group: "Sport" },
  { id: 155, name: "RS Sports 3 BR", url: "https://video07.logicahost.com.br/rssports03/rssports03/playlist.m3u8", country: "Brazil", countrySlug: "brazil", countryFlag: "🇧🇷", group: "Sport" },
  { id: 156, name: "RS Sports 4 BR", url: "https://video07.logicahost.com.br/rssports04/rssports04/playlist.m3u8", country: "Brazil", countrySlug: "brazil", countryFlag: "🇧🇷", group: "Sport" },
  { id: 157, name: "RS Sports 5 BR", url: "https://video03.logicahost.com.br/rssports5/rssports5/playlist.m3u8", country: "Brazil", countrySlug: "brazil", countryFlag: "🇧🇷", group: "Sport" },
  { id: 158, name: "RS PREMIERE BR", url: "https://video03.logicahost.com.br/rspremiere/rspremiere/playlist.m3u8", country: "Brazil", countrySlug: "brazil", countryFlag: "🇧🇷", group: "Sport" },
  { id: 159, name: "BEIN SPORTS Extra ES", url: "https://bein-esp-xumo.amagi.tv/playlist.m3u8", country: "Spain", countrySlug: "spain", countryFlag: "🇪🇸", group: "Sport" },
  { id: 160, name: "FOX SPORTS Premium Latino", url: "https://tv.topmediatv.net:25463/live/TopMediaWeb/bOteTR8ED1/375.m3u8", country: "International", countrySlug: "international", countryFlag: "🌍", group: "Sport" },
  { id: 161, name: "USA NBA TV", url: "https://tv.topmediatv.net:25463/live/TopMediaWeb/bOteTR8ED1/402.m3u8", country: "USA", countrySlug: "usa", countryFlag: "🇺🇸", group: "Sport" },
  { id: 162, name: "USA Fox Soccer Plus", url: "https://tv.topmediatv.net:25463/live/TopMediaWeb/bOteTR8ED1/3414.m3u8", country: "USA", countrySlug: "usa", countryFlag: "🇺🇸", group: "Sport" },
  { id: 163, name: "Gol TV", url: "http://38.44.109.41:8003/play/a02h/index.m3u8", country: "International", countrySlug: "international", countryFlag: "🌍", group: "Sport" },
  { id: 164, name: "Mundial NBC Universo", url: "http://190.11.225.124:5000/live/universo_hd/playlist.m3u8", country: "USA", countrySlug: "usa", countryFlag: "🇺🇸", group: "Entertainment" },
  { id: 165, name: "Mundial Azteca UNO MX", url: "http://38.44.109.41:8003/play/a033/index.m3u8", country: "Mexico", countrySlug: "mexico", countryFlag: "🇲🇽", group: "Entertainment" },
  { id: 166, name: "Azteca 7 MX", url: "https://estrellatv-roku.amagi.tv/playlist.m3u8", country: "Mexico", countrySlug: "mexico", countryFlag: "🇲🇽", group: "Entertainment" },
  { id: 167, name: "BeiN Sports Extra INT", url: "https://bein-esp-xumo.amagi.tv/playlistR720P.m3u8", country: "International", countrySlug: "international", countryFlag: "🌍", group: "Sport" },
  { id: 168, name: "Red Bull TV", url: "http://rbmn-live.akamaized.net/hls/live/590964/BoRB-AT/master_3360.m3u8", country: "International", countrySlug: "international", countryFlag: "🌍", group: "Sport" },
  { id: 169, name: "TyC Sports ARG 2", url: "http://38.44.109.41:8003/play/a02l/index.m3u8", country: "Argentina", countrySlug: "argentina", countryFlag: "🇦🇷", group: "Sport" },
  { id: 170, name: "Tango Sports 4 ARG", url: "http://190.7.19.197:232/play/a037/index.m3u8", country: "Argentina", countrySlug: "argentina", countryFlag: "🇦🇷", group: "Sport" },
];

export function getCountries() {
  const map = new Map<string, { country: string; countrySlug: string; countryFlag: string; count: number }>();
  channels.forEach(ch => {
    if (!map.has(ch.countrySlug)) {
      map.set(ch.countrySlug, { country: ch.country, countrySlug: ch.countrySlug, countryFlag: ch.countryFlag, count: 0 });
    }
    map.get(ch.countrySlug)!.count++;
  });
  return Array.from(map.values()).sort((a, b) => b.count - a.count);
}

export function getChannelsByCountry(slug: string) {
  return channels.filter(ch => ch.countrySlug === slug);
}

export function getChannelById(id: number) {
  return channels.find(ch => ch.id === id);
}
